apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: react-fastapi-prod

namePrefix: prod-

commonLabels:
  environment: production

patchesStrategicMerge:
  - deployment-patch.yaml

replicas:
  - name: backend
    count: 3
  - name: frontend
    count: 2

images:
  - name: quay.io/cfchase/react-fastapi-backend
    newTag: v1.0.0
  - name: quay.io/cfchase/react-fastapi-frontend
    newTag: v1.0.0