apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - backend-deployment.yaml
  - frontend-deployment.yaml
  - backend-service.yaml
  - frontend-service.yaml
  - route.yaml

commonLabels:
  app.kubernetes.io/name: react-fastapi-template
  app.kubernetes.io/version: "1.0.0"

images:
  - name: quay.io/your-org/react-fastapi-backend
    newTag: latest
  - name: quay.io/your-org/react-fastapi-frontend
    newTag: latest