apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: react-fastapi-dev

commonLabels:
  environment: development

patchesStrategicMerge:
  - deployment-patch.yaml

images:
  - name: quay.io/cfchase/react-fastapi-backend
    newTag: latest
  - name: quay.io/cfchase/react-fastapi-frontend
    newTag: latest