apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: react-fastapi-dev

namePrefix: dev-

commonLabels:
  environment: development

patchesStrategicMerge:
  - deployment-patch.yaml

images:
  - name: quay.io/your-org/react-fastapi-backend
    newTag: dev
  - name: quay.io/your-org/react-fastapi-frontend
    newTag: dev